name: numberpicker
version: 0.1.1
description: NumberPicker is a widget allowing user to choose numbers by scrolling spinners.
author: Marcin Szalek <marcinszalek1@gmail.com>
homepage: https://github.com/MarcinusX/NumberPicker

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true